// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.example.proto;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.proto.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string resonse_info = 1;</code>
   * @return The resonseInfo.
   */
  java.lang.String getResonseInfo();
  /**
   * <code>string resonse_info = 1;</code>
   * @return The bytes for resonseInfo.
   */
  com.google.protobuf.ByteString
      getResonseInfoBytes();
}
