// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.example.proto;

public interface StreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.proto.StreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_inof = 1;</code>
   * @return The requestInof.
   */
  java.lang.String getRequestInof();
  /**
   * <code>string request_inof = 1;</code>
   * @return The bytes for requestInof.
   */
  com.google.protobuf.ByteString
      getRequestInofBytes();
}
